export const projects = [
  {
    title: "VoteSphere - Django Voting System",
    description: "A Django-based e-voting system with roles for admin, election officers, presiding officers, and voters. Secure and scalable for campus elections.",
    image: "/images/votesphere.png",
    tags: ["Django", "Python", "Bootstrap", "HTML", "CSS", "JavaScript"],
    visit: "https://django-campus-voting.onrender.com/",
    source: "https://github.com/muhdzaheermv/django-campus-voting",
    id: 0,
  },
  {
    title: "Django Weather App",
    description: "Responsive weather application using Django and OpenWeatherMap API to fetch real-time forecasts. Ideal for beginners learning API and backend integration.",
    image: "/images/weather.png",
    tags: ["Django", "Python", "API", "Bootstrap", "HTML", "CSS"],
    visit: "https://django-weather-app-vtgd.onrender.com/",
    source: "https://github.com/muhdzaheermv/django-weather-app",
    id: 1,
  },
  {
    title: "React Portfolio",
    description: "A modern personal portfolio website built using ReactJS. Fully responsive, showcasing projects, skills, and contact information with smooth UI.",
    image: "/images/portfolio2.png",
    tags: ["React", "JavaScript", "CSS"],
    visit: "https://zaheermv.vercel.app/",
    source: "https://github.com/muhdzaheermv/reactjs-portfolio-website",
    id: 2,
  },
  {
    title: "Bank Landing Page (React + Tailwind + Vite)",
    description: "Fully responsive bank landing page built with React, Tailwind CSS, and Vite. Clean UI and fast load performance ideal for fintech showcases.",
    image: "/images/bank.png",
    tags: ["React", "Tailwind CSS", "Vite", "JavaScript"],
    visit: "https://muhdzaheermv.github.io/bank-landing-react-vite-tailwind/",
    source: "https://github.com/muhdzaheermv/bank-landing-react-vite-tailwind",
    id: 3,
  },
  {
    title: "Nike Website (React + Tailwind)",
    description: "Responsive Nike-inspired eCommerce landing page built using React and Tailwind CSS. Great for learning layout structure and component design.",
    image: "/images/nike.png",
    tags: ["React", "Tailwind CSS", "JavaScript"],
    visit: "https://nike-website-react-tailwind-sooty.vercel.app/",
    source: "https://github.com/muhdzaheermv/nike-website-react-tailwind",
    id: 4,
  },
  {
    title: "EV-Olution Landing Page",
    description: "React-based electric vehicle landing page featuring smooth UI, responsive layout, and optimized design elements. Great for automotive startups.",
    image: "/images/ev.png",
    tags: ["React", "CSS", "JavaScript"],
    visit: "https://muhdzaheermv.github.io/ev-olution-car-landing-reactjs/",
    source: "https://github.com/muhdzaheermv/ev-olution-car-landing-reactjs",
    id: 5,
  },
  {
    title: "Restaurant Website (ReactJS)",
    description: "A fully responsive restaurant website built with ReactJS. Great UI layout showcasing menu, contact, and home sections with elegant transitions.",
    image: "/images/restaurant.png",
    tags: ["React", "JavaScript", "CSS"],
    visit: "https://restaurent-react-website.vercel.app/",
    source: "https://github.com/muhdzaheermv/restaurant-react-website",
    id: 6,
  },
  {
    title: "Movie App (ReactJS)",
    description: "ReactJS-based movie search app using external API. Explore trending titles, search bar functionality, and component-based architecture for learning.",
    image: "/images/movie.png",
    tags: ["React", "JavaScript", "CSS", "API"],
    visit: "https://movie-app-beryl-six-33.vercel.app/",
    source: "https://github.com/muhdzaheermv/movie-app",
    id: 7,
  },
  {
    title: "React GPT3 Landing Page",
    description: "A responsive landing page UI built using ReactJS and inspired by GPT-3. Features animation, structured layout, and modern styling for practice.",
    image: "/images/gpt.png",
    tags: ["React", "CSS", "JavaScript"],
    visit: "https://muhdzaheermv.github.io/react-gpt3-landing-page/",
    source: "https://github.com/muhdzaheermv/react-gpt3-landing-page",
    id: 8,
  },
  {
    title: "WebZycle Thumbnail Agency",
    description: "Responsive landing page for a YouTube thumbnail agency built using HTML, CSS, and JavaScript. Clean layout with attention-grabbing call to action.",
    image: "/images/webzycle.png",
    tags: ["HTML", "CSS", "JavaScript"],
    visit: "https://webzycle.vercel.app/",
    source: "https://github.com/muhdzaheermv/webzycle",
    id: 9,
  },
  {
    title: "Portfolio (HTML/CSS/JS)",
    description: "A static personal portfolio website showcasing skills, contact info, and project previews. Built using HTML, CSS, and JavaScript for practice.",
    image: "/images/portfolio1.png",
    tags: ["HTML", "CSS", "JavaScript"],
    visit: "https://personal-portfolio-gules-theta.vercel.app/",
    source: "https://github.com/muhdzaheermv/personal-portfolio",
    id: 10,
  },
  {
    title: "YouTube Clone (HTML/CSS)",
    description: "A static clone of YouTube homepage using HTML and CSS. Practicing layout replication, spacing, and typography without interactivity.",
    image: "/images/youtube.png",
    tags: ["HTML", "CSS"],
    visit: "https://youtube-clone-html-css-rho.vercel.app/",
    source: "https://github.com/muhdzaheermv/youtube-clone-html-css",
    id: 11,
  },
  {
    title: "Spotify Clone (HTML/CSS)",
    description: "A static clone of Spotify’s homepage layout using HTML and CSS. Focused on flexbox layouts and design fundamentals. Not responsive.",
    image: "/images/spotify.png",
    tags: ["HTML", "CSS"],
    visit: "https://spotify-clone-html-css-eta.vercel.app/",
    source: "https://github.com/muhdzaheermv/spotify-clone-html-css",
    id: 12,
  },
  {
    title: "Simple Calculator (HTML/CSS/JS)",
    description: "A basic calculator built with HTML, CSS, and JavaScript. Supports simple arithmetic operations with a clean and intuitive interface.",
    image: "/images/calculator.png",
    tags: ["HTML", "CSS", "JavaScript"],
    visit: "https://calculator-mu-opal-13.vercel.app/",
    source: "https://github.com/muhdzaheermv/calculator",
    id: 13,
  },
  {
    title: "Rock Paper Scissors Game",
    description: "Classic rock-paper-scissors game with basic JavaScript logic. Play against the computer with score tracking and animated results.",
    image: "/images/rps.png",
    tags: ["HTML", "CSS", "JavaScript"],
    visit: "https://rock-paper-scissors-nine-lemon.vercel.app/",
    source: "https://github.com/muhdzaheermv/rock-paper-scissors",
    id: 14,
  },
  {
    title: "Birthday Reminder (ReactJS)",
    description: "Beginner ReactJS app that lists people’s birthdays. Useful for learning useState and props. Simple UI and component structure.",
    image: "/images/birthday.png",
    tags: ["React", "JavaScript", "CSS"],
    visit: "https://birthday-reminder-reactjs-app.vercel.app/",
    source: "https://github.com/muhdzaheermv/birthday-reminder",
    id: 15,
  },
  {
    title: "Funny Yes/No App",
    description: "Humorous web app with a floating 'No' button that avoids clicks. Built using JavaScript DOM events and basic CSS animation for fun.",
    image: "/images/funnyapp.png",
    tags: ["HTML", "CSS", "JavaScript"],
    visit: "https://byzaheer.vercel.app/",
    source: "https://github.com/muhdzaheermv/can-we-meet-funny-app",
    id: 16,
  },
   {
    title: "ChargeSpot - EV Charging & Service Booking System",
    description: "Full-stack Django app for booking EV charging/service slots, managing stations, feedback, and Razorpay payments.",
    image: "/images/chargespot.png",
    tags: ["Django", "Python", "Bootstrap", "HTML", "CSS", "JavaScript"],
    visit: "https://chargespot-ev.onrender.com/",
    source: "https://github.com/muhdzaheermv/chargespot-ev-slot-booking-using-django",
    id: 17,
  },
];

export const Certificates = [
  {
    certificate_title: "Fullstack Application Development Trainee - Grapesgenix",
    certificate_description: "6-month training in building full-stack web applications using Python Django, HTML, CSS, JavaScript, Bootstrap, Tailwind CSS, PostgreSQL, and SQLite. Developed REST APIs, integrated databases, and collaborated using Git in agile sprints.",
    image: "/images/certificate_1.jpg",
    source: "/images/certificate_1.pdf",
    id: 3
  },
  {
    certificate_title: "AI Internship - Grapesgenix Technical Solutions",
    certificate_description: "Completed a 4-month internship on Artificial Intelligence using Python, gaining hands-on experience in AI concepts and projects.",
    image: "/images/certificate_2.jpg",
    source: "/images/certificate_2.pdf",
    id: 1
  },
  {
    certificate_title: "Industrial Visit Certificate - InApp Technologies",
    certificate_description: "Completed an industrial visit at InApp Information Technologies, Trivandrum as part of BCA curriculum requirements.",
    image: "/images/certificate_3.jpg",
    source: "/images/certificate_3.pdf",
    id: 2
  }
];



export const TimeLineData = [
  { year: 2019, text: "Started with C & Java basics" },
  { year: 2020, text: "Began HTML/CSS, built small projects" },
  { year: 2021, text: "Mastered JavaScript, made mini-apps" },
  { year: 2022, text: "Explored MERN stack, built apps" },
  { year: 2023, text: "Learned React, Tailwind & Bootstrap" },
  { year: 2024, text: "Switched to Django, backend focused" },
  { year: 2025, text: "Freelance Django full-stack dev" },
];
